version: 2
jobs:
  build:
    docker:
      - image: frolvlad/alpine-gxx
    steps:
      - checkout
      - run: g++ --std=c++11 test.cpp -o test
      - run: ./test
      - run: g++ --std=c++11 main.cpp -o sum
      - store_artifacts:
          path: ./sum

